//! Provider-agnostic image-generation engine.
//!
//! Drives one image-generation call:
//!
//! 1. Merge per-call args with operator [`ImageDefaults`].
//! 2. Issue the upstream call via [`ImageProviderAdapter::generate`]
//!    with retry on transient errors.
//! 3. For each generated image, push the bytes into the gateway's
//!    `ContentStore` via [`mcpg_plugin_protocol::BackendHost::store_content`]
//!    — clients fetch the image on demand via MCP `resources/read`
//!    against the returned `mcpg-resource://<id>` URI.
//! 4. Return a structured response: `{images: [{image_uri,
//!    mime_type, revised_prompt?}]}` (always an array, even for
//!    `n=1`).

use std::sync::Arc;
use std::time::Duration;

use mcpg_plugin_protocol::{BackendError, BackendHost, BackendInvocationContext};
use serde_json::{Value, json};
use tracing::{debug, instrument, warn};

use crate::embedding_config::EmbeddingRetrySpec;
use crate::error::ProviderError;
use crate::image::{ImageProviderAdapter, NormalizedImageRequest};
use crate::image_config::ImageExecutionSpec;

pub struct ImageEngine {
    pub backend_name: String,
    pub adapter: Arc<dyn ImageProviderAdapter>,
    pub spec: ImageExecutionSpec,
    /// Host capability — the engine pushes generated bytes through
    /// `BackendHost::store_content`. The host is required (not
    /// optional): without it the engine couldn't return resource
    /// URIs and operators would have to inline base64 bytes in tool
    /// results, which defeats the design.
    pub host: Arc<dyn BackendHost>,
}

impl std::fmt::Debug for ImageEngine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ImageEngine")
            .field("backend_name", &self.backend_name)
            .field("provider", &self.adapter.label())
            .field("model", &self.spec.model)
            .finish()
    }
}

impl ImageEngine {
    /// Run one image-generation call.
    ///
    /// `args` shape:
    /// ```json
    /// {
    ///   "prompt": "a cat sitting on a chair",
    ///   "size": "1024x1024",   // optional, falls back to defaults.size
    ///   "quality": "hd",       // optional
    ///   "style": "vivid",      // optional
    ///   "n": 1                 // optional, defaults to defaults.n or 1
    /// }
    /// ```
    ///
    /// Returns:
    /// ```json
    /// {
    ///   "images": [
    ///     {
    ///       "image_uri": "mcpg-resource://hash:abc…",
    ///       "mime_type": "image/png",
    ///       "revised_prompt": "..."
    ///     }
    ///   ]
    /// }
    /// ```
    #[instrument(skip(self, args), fields(binding = %self.backend_name, provider = %self.adapter.label(), model = %self.spec.model))]
    pub async fn execute(
        &self,
        args: &Value,
        request_id: &str,
        session_id: Option<&str>,
    ) -> Result<Value, BackendError> {
        let prompt = args.get("prompt").and_then(|v| v.as_str()).ok_or_else(|| {
            BackendError::InvalidSpec {
                message: "image generation args must include `prompt` (string)".into(),
            }
        })?;
        if prompt.trim().is_empty() {
            return Err(BackendError::InvalidSpec {
                message: "`prompt` must not be empty".into(),
            });
        }

        let n = arg_u32(args, "n").unwrap_or_else(|| self.spec.defaults.n.unwrap_or(1));
        if n == 0 {
            return Err(BackendError::InvalidSpec {
                message: "`n` must be >= 1".into(),
            });
        }
        let size = arg_string(args, "size").or_else(|| self.spec.defaults.size.clone());
        let quality = arg_string(args, "quality").or_else(|| self.spec.defaults.quality.clone());
        let style = arg_string(args, "style").or_else(|| self.spec.defaults.style.clone());
        let seed = args.get("seed").and_then(|v| v.as_i64());
        let negative_prompt = arg_string(args, "negative_prompt")
            .or_else(|| self.spec.defaults.negative_prompt.clone());
        let output_format =
            arg_string(args, "output_format").or_else(|| self.spec.defaults.output_format.clone());

        let request = NormalizedImageRequest {
            model: self.spec.model.clone(),
            prompt: prompt.to_owned(),
            n,
            size,
            quality,
            style,
            seed,
            negative_prompt,
            output_format,
        };

        let started = std::time::Instant::now();
        let resp = call_with_retry(
            self.adapter.as_ref(),
            &request,
            self.spec.timeout(),
            &self.spec.retry,
        )
        .await
        .map_err(|e| binding_error_from_provider(&self.backend_name, e))?;
        let elapsed = started.elapsed();

        metrics::histogram!(
            "mcpg_image_call_seconds",
            "backend" => self.backend_name.clone(),
            "provider" => self.adapter.label().to_string(),
            "model" => self.spec.model.clone(),
        )
        .record(elapsed.as_secs_f64());
        metrics::counter!(
            "mcpg_image_calls_total",
            "backend" => self.backend_name.clone(),
            "provider" => self.adapter.label().to_string(),
            "model" => self.spec.model.clone(),
            "status" => "ok",
        )
        .increment(1);
        metrics::counter!(
            "mcpg_image_generated_total",
            "backend" => self.backend_name.clone(),
            "provider" => self.adapter.label().to_string(),
            "model" => self.spec.model.clone(),
        )
        .increment(resp.images.len() as u64);

        let host_ctx = BackendInvocationContext::root(
            request_id,
            session_id.map(|s| s.to_owned()),
            self.backend_name.clone(),
        );

        let mut out_images: Vec<Value> = Vec::with_capacity(resp.images.len());
        for img in resp.images {
            let resource = self
                .host
                .store_content(
                    &host_ctx,
                    img.bytes,
                    img.mime_type.clone(),
                    None, // No TTL — operators wanting expiry use the cache layer.
                )
                .await
                .map_err(|e| BackendError::Transport {
                    message: format!("store generated image: {e}"),
                })?;
            let mut entry = json!({
                "image_uri": resource.uri,
                "mime_type": img.mime_type,
            });
            if let Some(rp) = img.revised_prompt {
                entry["revised_prompt"] = json!(rp);
            }
            out_images.push(entry);
        }

        Ok(json!({"images": out_images}))
    }
}

fn arg_string(args: &Value, key: &str) -> Option<String> {
    args.get(key).and_then(|v| v.as_str()).map(|s| s.to_owned())
}

fn arg_u32(args: &Value, key: &str) -> Option<u32> {
    args.get(key)
        .and_then(|v| v.as_u64())
        .and_then(|n| u32::try_from(n).ok())
}

async fn call_with_retry(
    adapter: &dyn ImageProviderAdapter,
    request: &NormalizedImageRequest,
    timeout: Duration,
    retry: &EmbeddingRetrySpec,
) -> Result<crate::image::NormalizedImageResponse, ProviderError> {
    let mut attempt: u32 = 0;
    loop {
        attempt += 1;
        let result = adapter.generate(request, timeout).await;
        match result {
            Ok(resp) => return Ok(resp),
            Err(err) if attempt >= retry.max_attempts || !err.is_retryable() => {
                if !err.is_retryable() {
                    debug!(?err, "image error not retryable");
                } else {
                    warn!(
                        ?err,
                        attempt,
                        max = retry.max_attempts,
                        "image retries exhausted"
                    );
                }
                return Err(err);
            }
            Err(err) => {
                let backoff_ms = std::cmp::min(
                    retry.initial_backoff_ms.saturating_mul(1 << (attempt - 1)),
                    retry.max_backoff_ms,
                );
                debug!(?err, attempt, backoff_ms, "image retry");
                tokio::time::sleep(Duration::from_millis(backoff_ms)).await;
            }
        }
    }
}

fn binding_error_from_provider(binding: &str, err: ProviderError) -> BackendError {
    match err {
        ProviderError::Network { message } => BackendError::Transport {
            message: format!("image {binding}: network: {message}"),
        },
        ProviderError::Server { message } => BackendError::Transport {
            message: format!("image {binding}: server: {message}"),
        },
        ProviderError::RateLimited { message } => BackendError::Transport {
            message: format!("image {binding}: rate-limited: {message}"),
        },
        ProviderError::AuthFailed { message } => BackendError::InvalidSpec {
            message: format!("image {binding}: auth: {message}"),
        },
        ProviderError::BadRequest { message } => BackendError::InvalidSpec {
            message: format!("image {binding}: bad request: {message}"),
        },
        ProviderError::ContextLimit { message } => BackendError::InvalidSpec {
            message: format!("image {binding}: context limit: {message}"),
        },
        ProviderError::Malformed { message } => BackendError::Transport {
            message: format!("image {binding}: malformed: {message}"),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::image::{GeneratedImage, NormalizedImageResponse};
    use async_trait::async_trait;
    use mcpg_plugin_protocol::BackendResource;
    use std::sync::atomic::{AtomicUsize, Ordering};

    /// Stub adapter returning a zero-byte image for each requested
    /// `n` so the engine's ContentStore round-trip is exercised.
    struct StubAdapter {
        call_count: Arc<AtomicUsize>,
        mime: &'static str,
        revised_prompt: Option<&'static str>,
    }

    impl std::fmt::Debug for StubAdapter {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.debug_struct("StubAdapter").finish()
        }
    }

    #[async_trait]
    impl ImageProviderAdapter for StubAdapter {
        fn label(&self) -> &'static str {
            "stub"
        }
        async fn generate(
            &self,
            request: &NormalizedImageRequest,
            _timeout: Duration,
        ) -> Result<NormalizedImageResponse, ProviderError> {
            self.call_count.fetch_add(1, Ordering::SeqCst);
            let mut images = Vec::with_capacity(request.n as usize);
            for i in 0..request.n {
                images.push(GeneratedImage {
                    bytes: bytes::Bytes::copy_from_slice(format!("imgbytes-{i}").as_bytes()),
                    mime_type: self.mime.to_owned(),
                    revised_prompt: self.revised_prompt.map(|s| s.to_owned()),
                });
            }
            Ok(NormalizedImageResponse { images })
        }
    }

    /// Stub host that records store_content calls and returns
    /// fake resource URIs.
    struct StubHost {
        stored: std::sync::Mutex<Vec<(String, usize)>>,
    }

    #[async_trait]
    impl BackendHost for StubHost {
        async fn invoke_tool(
            &self,
            _ctx: &BackendInvocationContext,
            _tool: &str,
            _args: &Value,
        ) -> Result<Value, mcpg_plugin_protocol::BackendHostError> {
            unreachable!("not used")
        }
        async fn store_content(
            &self,
            _ctx: &BackendInvocationContext,
            bytes: bytes::Bytes,
            mime_type: String,
            _ttl: Option<Duration>,
        ) -> Result<BackendResource, mcpg_plugin_protocol::BackendHostError> {
            let id = format!("hash:{}", self.stored.lock().unwrap().len());
            self.stored
                .lock()
                .unwrap()
                .push((mime_type.clone(), bytes.len()));
            Ok(BackendResource {
                id: id.clone(),
                uri: format!("mcpg-resource://{id}"),
                size_bytes: bytes.len(),
                mime_type,
                content_hash: format!("blake3:{id}"),
                expires_at_unix: None,
            })
        }
    }

    fn engine(
        n_default: Option<u32>,
        mime: &'static str,
        revised_prompt: Option<&'static str>,
    ) -> (ImageEngine, Arc<AtomicUsize>, Arc<StubHost>) {
        let call_count = Arc::new(AtomicUsize::new(0));
        let host = Arc::new(StubHost {
            stored: std::sync::Mutex::new(Vec::new()),
        });
        let engine = ImageEngine {
            backend_name: "test".into(),
            adapter: Arc::new(StubAdapter {
                call_count: call_count.clone(),
                mime,
                revised_prompt,
            }),
            spec: ImageExecutionSpec {
                model: "test-model".into(),
                timeout_ms: 1000,
                connect_timeout_ms: 1000,
                defaults: super::super::image_config::ImageDefaults {
                    n: n_default,
                    ..Default::default()
                },
                retry: Default::default(),
            },
            host: host.clone() as Arc<dyn BackendHost>,
        };
        (engine, call_count, host)
    }

    #[tokio::test]
    async fn execute_returns_resource_uri_for_single_image() {
        let (e, _, host) = engine(None, "image/png", None);
        let r = e
            .execute(&json!({"prompt": "a cat"}), "req-1", Some("sess-1"))
            .await
            .unwrap();
        let imgs = r["images"].as_array().unwrap();
        assert_eq!(imgs.len(), 1);
        assert!(
            imgs[0]["image_uri"]
                .as_str()
                .unwrap()
                .starts_with("mcpg-resource://")
        );
        assert_eq!(imgs[0]["mime_type"], "image/png");
        assert_eq!(host.stored.lock().unwrap().len(), 1);
    }

    #[tokio::test]
    async fn revised_prompt_passes_through() {
        let (e, _, _) = engine(None, "image/png", Some("a fluffy cat"));
        let r = e
            .execute(&json!({"prompt": "cat"}), "r", None)
            .await
            .unwrap();
        assert_eq!(r["images"][0]["revised_prompt"], "a fluffy cat");
    }

    #[tokio::test]
    async fn n_arg_overrides_defaults() {
        let (e, _, host) = engine(Some(1), "image/png", None);
        let r = e
            .execute(&json!({"prompt": "x", "n": 3}), "r", None)
            .await
            .unwrap();
        assert_eq!(r["images"].as_array().unwrap().len(), 3);
        assert_eq!(host.stored.lock().unwrap().len(), 3);
    }

    #[tokio::test]
    async fn missing_prompt_errors() {
        let (e, _, _) = engine(None, "image/png", None);
        let err = e.execute(&json!({}), "r", None).await.unwrap_err();
        assert!(matches!(err, BackendError::InvalidSpec { .. }));
    }

    #[tokio::test]
    async fn empty_prompt_errors() {
        let (e, _, _) = engine(None, "image/png", None);
        let err = e
            .execute(&json!({"prompt": "  "}), "r", None)
            .await
            .unwrap_err();
        assert!(matches!(err, BackendError::InvalidSpec { .. }));
    }

    #[tokio::test]
    async fn zero_n_errors() {
        let (e, _, _) = engine(None, "image/png", None);
        let err = e
            .execute(&json!({"prompt": "x", "n": 0}), "r", None)
            .await
            .unwrap_err();
        assert!(matches!(err, BackendError::InvalidSpec { .. }));
    }

    #[tokio::test]
    async fn jpeg_mime_passes_through() {
        let (e, _, _) = engine(None, "image/jpeg", None);
        let r = e.execute(&json!({"prompt": "x"}), "r", None).await.unwrap();
        assert_eq!(r["images"][0]["mime_type"], "image/jpeg");
    }
}
